using System.IO;
using System.Net.Mail;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SGL.JudgeDredd.App.Services.Auth;
using SGL.JudgeDredd.Shared.Logging;

namespace SGL.JudgeDredd.App.ViewModels;

public partial class RegisterViewModel : ViewModelBase
{
    private readonly AuthService _authService;
    private const string AdminEmail = "syntheticgamelabs@gmail.com";

    [ObservableProperty]
    private string _username = string.Empty;

    [ObservableProperty]
    private string _email = string.Empty;

    private string _password = string.Empty;
    public string Password
    {
        get => _password;
        set => SetProperty(ref _password, value);
    }

    private string _confirmPassword = string.Empty;
    public string ConfirmPassword
    {
        get => _confirmPassword;
        set => SetProperty(ref _confirmPassword, value);
    }

    [ObservableProperty]
    private bool _hasAcceptedTerms;

    [ObservableProperty]
    private string _errorMessage = string.Empty;

    [ObservableProperty]
    private bool _hasError;

    [ObservableProperty]
    private bool _isRegistering;

    public event EventHandler<string>? RegistrationSuccessful;
    public event EventHandler? NavigateToLogin;

    public RegisterViewModel(AuthService authService)
    {
        _authService = authService;
        Title = "Create Account";
    }

    [RelayCommand]
    private async Task RegisterAsync()
    {
        HasError = false;

        if (string.IsNullOrWhiteSpace(Username) || Username.Length < 3)
        {
            ErrorMessage = "Username must be at least 3 characters.";
            HasError = true;
            return;
        }

        if (string.IsNullOrWhiteSpace(Email) || !Email.Contains('@'))
        {
            ErrorMessage = "Please enter a valid email address.";
            HasError = true;
            return;
        }

        if (string.IsNullOrWhiteSpace(Password) || Password.Length < 4)
        {
            ErrorMessage = "Password must be at least 4 characters.";
            HasError = true;
            return;
        }

        if (Password != ConfirmPassword)
        {
            ErrorMessage = "Passwords do not match.";
            HasError = true;
            return;
        }

        if (!HasAcceptedTerms)
        {
            ErrorMessage = "You must accept the EULA to create an account.";
            HasError = true;
            return;
        }

        IsRegistering = true;

        try
        {
            var (success, message) = await _authService.RegisterAsync(Username, Password, Email);

            if (success)
            {
                // Send notification to admin (fire-and-forget, don't block registration)
                _ = NotifyAdminAsync(Username, Email);
                RegistrationSuccessful?.Invoke(this, message);
            }
            else
            {
                ErrorMessage = message;
                HasError = true;
            }
        }
        catch (Exception ex)
        {
            ErrorMessage = $"Registration failed: {ex.Message}";
            HasError = true;
        }
        finally
        {
            IsRegistering = false;
        }
    }

    private static async Task NotifyAdminAsync(string username, string userEmail)
    {
        try
        {
            // Save registration notification to local file for admin review
            var notifDir = Path.Combine(AppContext.BaseDirectory, "data", "notifications");
            Directory.CreateDirectory(notifDir);
            var notifFile = Path.Combine(notifDir,
                $"registration_{DateTime.UtcNow:yyyyMMdd_HHmmss}_{username}.txt");

            var content = $"""
                NEW USER REGISTRATION - SGL SyntheticAI
                ==========================================
                Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC
                Username: {username}
                Email: {userEmail}
                Admin Contact: {AdminEmail}
                Machine: {Environment.MachineName}

                This notification was generated by SGL SyntheticAI Security Suite.
                Contact admin at {AdminEmail} to manage this account.
                """;

            await File.WriteAllTextAsync(notifFile, content);
            SglLogger.Information("Registration notification saved for user {Username} ({Email})", username, userEmail);

            // Attempt SMTP email to admin (best-effort, requires SMTP config)
            try
            {
                using var smtp = new SmtpClient("smtp.gmail.com", 587)
                {
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Timeout = 10000,
                };

                var mail = new MailMessage
                {
                    From = new MailAddress("noreply@syntheticai.local", "SGL SyntheticAI"),
                    Subject = $"[SGL-SA] New User Registration: {username}",
                    Body = content,
                    IsBodyHtml = false,
                };
                mail.To.Add(AdminEmail);

                await smtp.SendMailAsync(mail);
            }
            catch
            {
                // SMTP requires credentials - local file notification is the primary method
                SglLogger.Information("Email notification skipped (SMTP not configured). Local notification saved.");
            }
        }
        catch (Exception ex)
        {
            SglLogger.Error("Failed to save registration notification", ex);
        }
    }

    [RelayCommand]
    private void NavigateToLoginAction()
    {
        NavigateToLogin?.Invoke(this, EventArgs.Empty);
    }
}
